version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Web.Dockerfile
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - 5000:5000
    volumes:
      - ./project.csproj:/usr/src/app/project.csproj
      - ./Program.cs:/usr/src/app/Program.cs
      - ./Config:/usr/src/app/Config
      - ./Routes:/usr/src/app/Routes
      - ./wwwroot:/usr/src/app/wwwroot
  builder:
    build:
      context: .
      dockerfile: ./docker/Builder.Dockerfile
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./gulpfile.js:/usr/src/app/gulpfile.js
      - ./Routes:/usr/src/app/Routes
      - ./styles:/usr/src/app/styles
      - ./wwwroot:/usr/src/app/wwwroot