version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Web.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - 5000:5000
    volumes:
      - ./project.csproj:/usr/src/app/project.csproj
      - ./Program.cs:/usr/src/app/Program.cs
      - ./Web:/usr/src/app/Web
      - ./Logic:/usr/src/app/Logic
      - ./Logic.Json:/usr/src/app/Logic.Json
  builder:
    build:
      context: .
      dockerfile: ./docker/Builder.Dockerfile
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./gulpfile.js:/usr/src/app/gulpfile.js
      - ./Web:/usr/src/app/Web